// Generated Alloy model for state machine: ATM_System
// Generated by upml-rs
// Alloy structural verification model

// Signatures (Types)

abstract sig State {
  transitions: set Transition
}

one sig WithdrawCash extends State {} // WithdrawCash
one sig Authenticated extends State {} // Authenticated
one sig CheckBalance extends State {} // CheckBalance
one sig PinEntry extends State {} // PinEntry
one sig Idle extends State {} // Idle
one sig CardBlocked extends State {} // CardBlocked
one sig CardInserted extends State {} // CardInserted
one sig DispensingCash extends State {} // DispensingCash
one sig SelectTransaction extends State {} // SelectTransaction

abstract sig Event {}
one sig pin_correct extends Event {} // pin_correct
one sig insert_card extends Event {} // insert_card
one sig balance_shown extends Event {} // balance_shown
one sig select_withdraw extends Event {} // select_withdraw
one sig authenticated extends Event {} // authenticated
one sig cancel extends Event {} // cancel
one sig amount_invalid extends Event {} // amount_invalid
one sig card_invalid extends Event {} // card_invalid
one sig card_valid extends Event {} // card_valid
one sig pin_incorrect extends Event {} // pin_incorrect
one sig cash_dispensed extends Event {} // cash_dispensed
one sig select_balance extends Event {} // select_balance
one sig timeout extends Event {} // timeout
one sig amount_valid extends Event {} // amount_valid

sig Transition {
  from: one State,
  to: one State,
  event: one Event,
  guard: lone String,
  effect: lone String
}

one sig StateMachine {
  states: set State,
  initialStates: set State,
  finalStates: set State,
  transitions: set Transition
}

// Facts (Structural Constraints)

fact StateMachineStructure {
  // All states belong to the state machine
  StateMachine.states = State

  // All transitions belong to the state machine
  StateMachine.transitions = Transition

  // Transitions are owned by their source states
  all t: Transition | t in t.from.transitions

  // Initial and final states are subsets of all states
  StateMachine.initialStates in StateMachine.states
  StateMachine.finalStates in StateMachine.states
}

fact SpecificConstraints {
  StateMachine.initialStates = Idle
  no StateMachine.finalStates

  // Specific transitions from the state machine
  some t: Transition | t.from = CardInserted and t.to = PinEntry and t.event = card_valid // t_CardInserted_to_PinEntry
  some t: Transition | t.from = CardInserted and t.to = Idle and t.event = card_invalid // t_CardInserted_to_Idle
  some t: Transition | t.from = DispensingCash and t.to = Idle and t.event = cash_dispensed // t_DispensingCash_to_Idle
  some t: Transition | t.from = SelectTransaction and t.to = WithdrawCash and t.event = select_withdraw // t_SelectTransaction_to_WithdrawCash
  some t: Transition | t.from = SelectTransaction and t.to = CheckBalance and t.event = select_balance // t_SelectTransaction_to_CheckBalance
  some t: Transition | t.from = SelectTransaction and t.to = Idle and t.event = cancel // t_SelectTransaction_to_Idle
  some t: Transition | t.from = CheckBalance and t.to = SelectTransaction and t.event = balance_shown // t_CheckBalance_to_SelectTransaction
  some t: Transition | t.from = PinEntry and t.to = Authenticated and t.event = pin_correct // t_PinEntry_to_Authenticated
  some t: Transition | t.from = PinEntry and t.to = CardBlocked and t.event = pin_incorrect // t_PinEntry_to_CardBlocked
  some t: Transition | t.from = PinEntry and t.to = PinEntry and t.event = pin_incorrect // t_PinEntry_to_PinEntry
  some t: Transition | t.from = Authenticated and t.to = SelectTransaction and t.event = authenticated // t_Authenticated_to_SelectTransaction
  some t: Transition | t.from = Idle and t.to = CardInserted and t.event = insert_card // t_Idle_to_CardInserted
  some t: Transition | t.from = WithdrawCash and t.to = DispensingCash and t.event = amount_valid // t_WithdrawCash_to_DispensingCash
  some t: Transition | t.from = WithdrawCash and t.to = SelectTransaction and t.event = amount_invalid // t_WithdrawCash_to_SelectTransaction
  some t: Transition | t.from = CardBlocked and t.to = Idle and t.event = timeout // t_CardBlocked_to_Idle
}

// Predicates for Analysis

pred Reachable[s1, s2: State] {
  s2 in s1.^(transitions.to)
}

pred WellFormed {
  // At least one initial state
  some StateMachine.initialStates

  // No orphaned states (except final states)
  all s: State - StateMachine.finalStates |
    some s.transitions or s in StateMachine.transitions.to

  // All states reachable from initial states
  all s: State | some init: StateMachine.initialStates |
    s = init or Reachable[init, s]
}

pred Deterministic {
  // No two transitions from same state with same event
  all s: State, e: Event |
    lone t: s.transitions | t.event = e
}

pred DeadlockFree {
  // All non-final states have outgoing transitions
  all s: State - StateMachine.finalStates |
    some s.transitions
}

// Behavioral Predicates

pred LivenessProperty {
  // From any initial state, a final state is reachable
  all init: StateMachine.initialStates |
    some final: StateMachine.finalStates |
      final = init or Reachable[init, final]
}

pred SafetyProperty {
  // No transition leads to an undefined state
  all t: Transition | t.to in StateMachine.states
}

// Assertions for Verification

// Check that well-formed state machines are deterministic
assert WellFormedImpliesDeterministic {
  WellFormed implies Deterministic
}

// Check that deterministic state machines are deadlock-free
assert DeterministicImpliesDeadlockFree {
  Deterministic implies DeadlockFree
}

// Check liveness property
assert LivenessHolds {
  WellFormed implies LivenessProperty
}

// Run Commands for Analysis

// Find a well-formed state machine instance
run WellFormed for 10 State, 8 Event, 15 Transition

// Find a deterministic state machine
run { WellFormed and Deterministic } for 10 State, 8 Event, 15 Transition

// Check assertions
check WellFormedImpliesDeterministic for 10 State, 8 Event, 15 Transition
check DeterministicImpliesDeadlockFree for 10 State, 8 Event, 15 Transition
check LivenessHolds for 10 State, 8 Event, 15 Transition
