// Generated Alloy model for state machine: test_simple_fsm
// Generated by upml-rs
// Alloy structural verification model

// Signatures (Types)

abstract sig State {
  transitions: set Transition
}

one sig Idle extends State {} // Idle
one sig Completed extends State {} // Completed
one sig Error extends State {} // Error
one sig Processing extends State {} // Processing

abstract sig Event {}
one sig Failure extends Event {} // Failure
one sig Finish extends Event {} // Finish
one sig Retry extends Event {} // Retry
one sig Start extends Event {} // Start

sig Transition {
  from: one State,
  to: one State,
  event: one Event,
  guard: lone String,
  effect: lone String
}

one sig StateMachine {
  states: set State,
  initialStates: set State,
  finalStates: set State,
  transitions: set Transition
}

// Facts (Structural Constraints)

fact StateMachineStructure {
  // All states belong to the state machine
  StateMachine.states = State

  // All transitions belong to the state machine
  StateMachine.transitions = Transition

  // Transitions are owned by their source states
  all t: Transition | t in t.from.transitions

  // Initial and final states are subsets of all states
  StateMachine.initialStates in StateMachine.states
  StateMachine.finalStates in StateMachine.states
}

fact SpecificConstraints {
  StateMachine.initialStates = Idle
  StateMachine.finalStates = Completed

  // Specific transitions from the state machine
  some t: Transition | t.from = Processing and t.to = Completed and t.event = Finish // t_Processing_to_Completed
  some t: Transition | t.from = Processing and t.to = Error and t.event = Failure // t_Processing_to_Error
  some t: Transition | t.from = Idle and t.to = Processing and t.event = Start // t_Idle_to_Processing
  some t: Transition | t.from = Error and t.to = Idle and t.event = Retry // t_Error_to_Idle
}

// Predicates for Analysis

pred Reachable[s1, s2: State] {
  s2 in s1.^(transitions.to)
}

pred WellFormed {
  // At least one initial state
  some StateMachine.initialStates

  // No orphaned states (except final states)
  all s: State - StateMachine.finalStates |
    some s.transitions or s in StateMachine.transitions.to

  // All states reachable from initial states
  all s: State | some init: StateMachine.initialStates |
    s = init or Reachable[init, s]
}

pred Deterministic {
  // No two transitions from same state with same event
  all s: State, e: Event |
    lone t: s.transitions | t.event = e
}

pred DeadlockFree {
  // All non-final states have outgoing transitions
  all s: State - StateMachine.finalStates |
    some s.transitions
}

// Behavioral Predicates

pred LivenessProperty {
  // From any initial state, a final state is reachable
  all init: StateMachine.initialStates |
    some final: StateMachine.finalStates |
      final = init or Reachable[init, final]
}

pred SafetyProperty {
  // No transition leads to an undefined state
  all t: Transition | t.to in StateMachine.states
}

// Assertions for Verification

// Check that well-formed state machines are deterministic
assert WellFormedImpliesDeterministic {
  WellFormed implies Deterministic
}

// Check that deterministic state machines are deadlock-free
assert DeterministicImpliesDeadlockFree {
  Deterministic implies DeadlockFree
}

// Check liveness property
assert LivenessHolds {
  WellFormed implies LivenessProperty
}

// Run Commands for Analysis

// Find a well-formed state machine instance
run WellFormed for 10 State, 8 Event, 15 Transition

// Find a deterministic state machine
run { WellFormed and Deterministic } for 10 State, 8 Event, 15 Transition

// Check assertions
check WellFormedImpliesDeterministic for 10 State, 8 Event, 15 Transition
check DeterministicImpliesDeadlockFree for 10 State, 8 Event, 15 Transition
check LivenessHolds for 10 State, 8 Event, 15 Transition
