/*
 * Generated Promela FSM model for state machine: test_complex_hsm
 * Generated by upml-rs
 */

/* Message types (events) */
mtype = {
    Complete,
    DataReady,
    EnterState,
    Error,
    ExitState,
    NullEvent,
    Process,
    ProcessComplete,
    SaveComplete,
    Start,
    StatusClear,
    StatusUpdate,
    Stop,
    Validate,
    ValidationComplete
};

/* State enumeration */
mtype = {
    state_DataProcessing,
    state_Idle,
    state_Loading,
    state_Processing,
    state_Ready,
    state_Saving,
    state_StatusActive,
    state_StatusIdle,
    state_ValidationPhase,
    state_Working
};

/* Global variables */
mtype currentState;
mtype event;
chan eventQueue = [16] of { mtype };
bool inTransition = false;

/* Main FSM process */
active proctype StateMachine() {
    currentState = state_Idle; 
    
    do
    :: eventQueue?event ->
        atomic {
            inTransition = true;
            
            /* State transitions */
            if
            :: (currentState == state_ValidationPhase && event == ValidationComplete) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_Idle && event == Process) ->
                    currentState = state_Processing;
            :: else -> skip
            fi
            if
            :: (currentState == state_Loading && event == DataReady) ->
                    currentState = state_Processing;
            :: else -> skip
            fi
            if
            :: (currentState == state_Ready && event == Start) ->
                    currentState = state_Working;
            :: else -> skip
            fi
            if
            :: (currentState == state_Working && event == Stop) ->
                    currentState = state_Ready;
            :: else -> skip
            fi
            if
            :: (currentState == state_DataProcessing && event == Validate) ->
                    currentState = state_ValidationPhase;
            :: else -> skip
            fi
            if
            :: (currentState == state_Saving && event == SaveComplete) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_StatusIdle && event == StatusUpdate) ->
                    currentState = state_StatusActive;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == ProcessComplete) ->
                    currentState = state_Saving;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == Error) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == Complete) ->
                    currentState = state_Idle;
            :: else -> skip
            fi
            if
            :: (currentState == state_StatusActive && event == StatusClear) ->
                    currentState = state_StatusIdle;
            :: else -> skip
            fi
            
            inTransition = false;
        }
    od
    
end_state:
    /* Final state reached - process terminates */
}

/* LTL Properties */
/* Basic liveness: eventually reach a final state */
ltl liveness { <>( currentState == state_ValidationPhase || currentState == state_Saving || currentState == state_Processing ) }
ltl safety { [](!inTransition -> <>inTransition) }
