/*
 * Generated Promela FSM model for state machine: test_concurrent
 * Generated by upml-rs
 */

/* Message types (events) */
mtype = {
    EnterState,
    EventA,
    EventB,
    ExitState,
    NullEvent
};

/* State enumeration */
mtype = {
    state_Active,
    state_StateA1,
    state_StateA2,
    state_StateB1,
    state_StateB2
};

/* Global variables */
mtype currentState;
mtype event;
chan eventQueue = [16] of { mtype };
bool inTransition = false;

/* Main FSM process */
active proctype StateMachine() {
    currentState = state_StateA1; 
    
    do
    :: eventQueue?event ->
        atomic {
            inTransition = true;
            
            /* State transitions */
            if
            :: (currentState == state_StateB1 && event == EventB) ->
                    currentState = state_StateB2;
            :: else -> skip
            fi
            if
            :: (currentState == state_StateA2 && event == NullEvent) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_StateA1 && event == EventA) ->
                    currentState = state_StateA2;
            :: else -> skip
            fi
            if
            :: (currentState == state_Active && event == NullEvent) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_StateB2 && event == NullEvent) ->
                    goto end_state;
            :: else -> skip
            fi
            
            inTransition = false;
        }
    od
    
end_state:
    /* Final state reached - process terminates */
}

/* LTL Properties */
/* Basic liveness: eventually reach a final state */
ltl liveness { <>( currentState == state_StateA2 || currentState == state_Active || currentState == state_StateB2 ) }
ltl safety { [](!inTransition -> <>inTransition) }
