/*
 * Generated Promela FSM model for state machine: test_activities
 * Generated by upml-rs
 */

/* Message types (events) */
mtype = {
    EnterState,
    ExitState,
    Failure,
    Finish,
    NullEvent,
    Retry,
    Start
};

/* State enumeration */
mtype = {
    state_Completed,
    state_Error,
    state_Idle,
    state_Processing
};

/* Global variables */
mtype currentState;
mtype event;
chan eventQueue = [16] of { mtype };
bool inTransition = false;

/* Main FSM process */
active proctype StateMachine() {
    currentState = state_Idle; 
    
    do
    :: eventQueue?event ->
        atomic {
            inTransition = true;
            
            /* State transitions */
            if
            :: (currentState == state_Idle && event == Start) ->
                if
                :: (ready) ->
                    /* Effect: initialize() */
                    /* initialize() */
                    /* Effect: start_timer() */
                    /* start_timer() */
                    currentState = state_Processing;
                :: else -> skip
                fi
            :: else -> skip
            fi
            if
            :: (currentState == state_Error && event == Retry) ->
                    /* Effect: reset_state() */
                    /* reset_state() */
                    currentState = state_Idle;
            :: else -> skip
            fi
            if
            :: (currentState == state_Completed && event == NullEvent) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == Finish) ->
                    /* Effect: cleanup() */
                    /* cleanup() */
                    /* Effect: stop_timer() */
                    /* stop_timer() */
                    currentState = state_Completed;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == Failure) ->
                if
                :: (error_count < 3) ->
                    /* Effect: log_error() */
                    /* log_error() */
                    currentState = state_Error;
                :: else -> skip
                fi
            :: else -> skip
            fi
            
            inTransition = false;
        }
    od
    
end_state:
    /* Final state reached - process terminates */
}

/* LTL Properties */
/* Basic liveness: eventually reach a final state */
ltl liveness { <>( currentState == state_Completed ) }
ltl safety { [](!inTransition -> <>inTransition) }
