// Generated Alloy model for state machine: test_complex_hsm
// Generated by upml-rs
// Alloy structural verification model

// Signatures (Types)

abstract sig State {
  transitions: set Transition
}

one sig Loading extends State {} // Loading
one sig StatusActive extends State {} // StatusActive
one sig Idle extends State {} // Idle
one sig Ready extends State {} // Ready
one sig DataProcessing extends State {} // DataProcessing
one sig StatusIdle extends State {} // StatusIdle
one sig Working extends State {} // Working
one sig Processing extends State {} // Processing
one sig ValidationPhase extends State {} // ValidationPhase
one sig Saving extends State {} // Saving

abstract sig Event {}
one sig StatusClear extends Event {} // StatusClear
one sig Complete extends Event {} // Complete
one sig Validate extends Event {} // Validate
one sig StatusUpdate extends Event {} // StatusUpdate
one sig DataReady extends Event {} // DataReady
one sig SaveComplete extends Event {} // SaveComplete
one sig Process extends Event {} // Process
one sig Stop extends Event {} // Stop
one sig Error extends Event {} // Error
one sig ProcessComplete extends Event {} // ProcessComplete
one sig Start extends Event {} // Start
one sig ValidationComplete extends Event {} // ValidationComplete

sig Transition {
  from: one State,
  to: one State,
  event: one Event,
  guard: lone String,
  effect: lone String
}

one sig StateMachine {
  states: set State,
  initialStates: set State,
  finalStates: set State,
  transitions: set Transition
}

// Facts (Structural Constraints)

fact StateMachineStructure {
  // All states belong to the state machine
  StateMachine.states = State

  // All transitions belong to the state machine
  StateMachine.transitions = Transition

  // Transitions are owned by their source states
  all t: Transition | t in t.from.transitions

  // Initial and final states are subsets of all states
  StateMachine.initialStates in StateMachine.states
  StateMachine.finalStates in StateMachine.states
}

fact SpecificConstraints {
  StateMachine.initialStates = DataProcessing + Ready + StatusIdle + Idle + Loading
  StateMachine.finalStates = Processing + Saving + ValidationPhase

  // Specific transitions from the state machine
  some t: Transition | t.from = Loading and t.to = Processing and t.event = DataReady // t_Loading_to_Processing
  some t: Transition | t.from = Idle and t.to = Processing and t.event = Process // t_Idle_to_Processing
  some t: Transition | t.from = StatusActive and t.to = StatusIdle and t.event = StatusClear // t_StatusActive_to_StatusIdle
  some t: Transition | t.from = Processing and t.to = Saving and t.event = ProcessComplete // t_Processing_to_Saving
  some t: Transition | t.from = Processing and t.to = Idle and t.event = Complete // t_Processing_to_Idle
  some t: Transition | t.from = Working and t.to = Ready and t.event = Stop // t_Working_to_Ready
  some t: Transition | t.from = DataProcessing and t.to = ValidationPhase and t.event = Validate // t_DataProcessing_to_ValidationPhase
  some t: Transition | t.from = Ready and t.to = Working and t.event = Start // t_Ready_to_Working
  some t: Transition | t.from = StatusIdle and t.to = StatusActive and t.event = StatusUpdate // t_StatusIdle_to_StatusActive
}

// Predicates for Analysis

pred Reachable[s1, s2: State] {
  s2 in s1.^(transitions.to)
}

pred WellFormed {
  // At least one initial state
  some StateMachine.initialStates

  // No orphaned states (except final states)
  all s: State - StateMachine.finalStates |
    some s.transitions or s in StateMachine.transitions.to

  // All states reachable from initial states
  all s: State | some init: StateMachine.initialStates |
    s = init or Reachable[init, s]
}

pred Deterministic {
  // No two transitions from same state with same event
  all s: State, e: Event |
    lone t: s.transitions | t.event = e
}

pred DeadlockFree {
  // All non-final states have outgoing transitions
  all s: State - StateMachine.finalStates |
    some s.transitions
}

// Behavioral Predicates

pred LivenessProperty {
  // From any initial state, a final state is reachable
  all init: StateMachine.initialStates |
    some final: StateMachine.finalStates |
      final = init or Reachable[init, final]
}

pred SafetyProperty {
  // No transition leads to an undefined state
  all t: Transition | t.to in StateMachine.states
}

// Assertions for Verification

// Check that well-formed state machines are deterministic
assert WellFormedImpliesDeterministic {
  WellFormed implies Deterministic
}

// Check that deterministic state machines are deadlock-free
assert DeterministicImpliesDeadlockFree {
  Deterministic implies DeadlockFree
}

// Check liveness property
assert LivenessHolds {
  WellFormed implies LivenessProperty
}

// Run Commands for Analysis

// Find a well-formed state machine instance
run WellFormed for 10 State, 8 Event, 15 Transition

// Find a deterministic state machine
run { WellFormed and Deterministic } for 10 State, 8 Event, 15 Transition

// Check assertions
check WellFormedImpliesDeterministic for 10 State, 8 Event, 15 Transition
check DeterministicImpliesDeadlockFree for 10 State, 8 Event, 15 Transition
check LivenessHolds for 10 State, 8 Event, 15 Transition
