(*
 * Generated TLA+/PlusCal FSM model for state machine: test_simple_fsm
 * Generated by upml-rs
 *)

---- MODULE test_simple_fsm ----
EXTENDS Naturals, Sequences, TLC

\* Constants
CONSTANTS
    Completed,
    Error,
    Idle,
    Processing

CONSTANTS
    EnterState,
    ExitState,
    Failure,
    Finish,
    NullEvent,
    Retry,
    Start

\* Variables
VARIABLES
    currentState,    \* Current state of the state machine
    eventQueue,      \* Queue of pending events
    inTransition     \* Flag indicating if a transition is in progress

\* Type invariants
States == {Completed, Error, Idle, Processing, "FINAL"}
Events == {EnterState, ExitState, Failure, Finish, NullEvent, Retry, Start}

TypeInvariant ==
    /\ currentState \in States
    /\ eventQueue \in Seq(Events)
    /\ inTransition \in BOOLEAN

\* Initial state predicate
Init ==
    /\ currentState = Idle
    /\ eventQueue = <<>>
    /\ inTransition = FALSE

\* Transition actions
\* Transition from Processing to Completed on Finish
Transition_Processing_Completed ==
    /\ currentState = Processing
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Finish
    /\ inTransition = FALSE
    /\ currentState' = Completed
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Processing to Error on Failure
Transition_Processing_Error ==
    /\ currentState = Processing
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Failure
    /\ inTransition = FALSE
    /\ currentState' = Error
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Error to Idle on Retry
Transition_Error_Idle ==
    /\ currentState = Error
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Retry
    /\ inTransition = FALSE
    /\ currentState' = Idle
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Idle to Processing on Start
Transition_Idle_Processing ==
    /\ currentState = Idle
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Start
    /\ inTransition = FALSE
    /\ currentState' = Processing
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Completed to [*] on NullEvent
Transition_Completed_Final ==
    /\ currentState = Completed
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = NullEvent
    /\ inTransition = FALSE
    /\ currentState' = "FINAL"
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE


\* Next state relation
Next ==
    \/ Transition_Processing_Completed
    \/ Transition_Processing_Error
    \/ Transition_Error_Idle
    \/ Transition_Idle_Processing
    \/ Transition_Completed_Final
    \/ UNCHANGED <<currentState, eventQueue, inTransition>>

\* Specification
Spec == Init /\ [][Next]_<<currentState, eventQueue, inTransition>>

\* Properties
THEOREM Spec => []TypeInvariant

\* Liveness: eventually reach a final state
Liveness == <>( currentState = Completed )
THEOREM Spec => Liveness

\* Safety: always in a valid state
Safety == [](currentState \in States)
THEOREM Spec => Safety
====
