/*
 * Generated Promela FSM model for state machine: parsed_machine
 * Generated by upml-rs
 */

/* Message types (events) */
mtype = {
    ComputationComplete,
    CriticalError,
    EnterState,
    ErrorRecovered,
    ExitState,
    InitComplete,
    NullEvent,
    ProcessComplete,
    Retry,
    SaveComplete,
    Shutdown,
    Start,
    SystemShutdown,
    ValidationFailed,
    ValidationPassed
};

/* State enumeration */
mtype = {
    state_Computing,
    state_ErrorState,
    state_Initializing,
    state_Processing,
    state_Ready,
    state_Saving,
    state_Validating,
    state_ValidationError
};

/* Global variables */
mtype currentState;
mtype event;
chan eventQueue = [16] of { mtype };
bool inTransition = false;

/* Main FSM process */
active proctype StateMachine() {
    currentState = state_Initializing; 
    
    do
    :: eventQueue?event ->
        atomic {
            inTransition = true;
            
            /* State transitions */
            if
            :: (currentState == state_Validating && event == ValidationFailed) ->
                    currentState = state_ValidationError;
            :: else -> skip
            fi
            if
            :: (currentState == state_Validating && event == ValidationPassed) ->
                    currentState = state_Computing;
            :: else -> skip
            fi
            if
            :: (currentState == state_Computing && event == ComputationComplete) ->
                    currentState = state_Saving;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == ProcessComplete) ->
                    currentState = state_Ready;
            :: else -> skip
            fi
            if
            :: (currentState == state_Processing && event == CriticalError) ->
                    currentState = state_ErrorState;
            :: else -> skip
            fi
            if
            :: (currentState == state_Initializing && event == InitComplete) ->
                    currentState = state_Ready;
            :: else -> skip
            fi
            if
            :: (currentState == state_Ready && event == SystemShutdown) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_Ready && event == Start) ->
                    currentState = state_Processing;
            :: else -> skip
            fi
            if
            :: (currentState == state_Saving && event == SaveComplete) ->
                    goto end_state;
            :: else -> skip
            fi
            if
            :: (currentState == state_ValidationError && event == Retry) ->
                    currentState = state_Validating;
            :: else -> skip
            fi
            if
            :: (currentState == state_ErrorState && event == ErrorRecovered) ->
                    currentState = state_Ready;
            :: else -> skip
            fi
            if
            :: (currentState == state_ErrorState && event == Shutdown) ->
                    goto end_state;
            :: else -> skip
            fi
            
            inTransition = false;
        }
    od
    
end_state:
    /* Final state reached - process terminates */
}

/* LTL Properties */
/* Basic liveness: eventually reach a final state */
ltl liveness { <>( currentState == state_Saving || currentState == state_ErrorState || currentState == state_Ready ) }
ltl safety { [](!inTransition -> <>inTransition) }
