// Generated Alloy model for state machine: parsed_machine
// Generated by upml-rs
// Alloy structural verification model

// Signatures (Types)

abstract sig State {
  transitions: set Transition
}

one sig Computing extends State {} // Computing
one sig Ready extends State {} // Ready
one sig ValidationError extends State {} // ValidationError
one sig Saving extends State {} // Saving
one sig Validating extends State {} // Validating
one sig Initializing extends State {} // Initializing
one sig ErrorState extends State {} // ErrorState
one sig Processing extends State {} // Processing

abstract sig Event {}
one sig InitComplete extends Event {} // InitComplete
one sig Retry extends Event {} // Retry
one sig CriticalError extends Event {} // CriticalError
one sig ComputationComplete extends Event {} // ComputationComplete
one sig ValidationFailed extends Event {} // ValidationFailed
one sig Shutdown extends Event {} // Shutdown
one sig SystemShutdown extends Event {} // SystemShutdown
one sig ErrorRecovered extends Event {} // ErrorRecovered
one sig ProcessComplete extends Event {} // ProcessComplete
one sig SaveComplete extends Event {} // SaveComplete
one sig Start extends Event {} // Start
one sig ValidationPassed extends Event {} // ValidationPassed

sig Transition {
  from: one State,
  to: one State,
  event: one Event,
  guard: lone String,
  effect: lone String
}

one sig StateMachine {
  states: set State,
  initialStates: set State,
  finalStates: set State,
  transitions: set Transition
}

// Facts (Structural Constraints)

fact StateMachineStructure {
  // All states belong to the state machine
  StateMachine.states = State

  // All transitions belong to the state machine
  StateMachine.transitions = Transition

  // Transitions are owned by their source states
  all t: Transition | t in t.from.transitions

  // Initial and final states are subsets of all states
  StateMachine.initialStates in StateMachine.states
  StateMachine.finalStates in StateMachine.states
}

fact SpecificConstraints {
  StateMachine.initialStates = Validating + Initializing
  StateMachine.finalStates = Saving + ErrorState + Ready

  // Specific transitions from the state machine
  some t: Transition | t.from = Validating and t.to = ValidationError and t.event = ValidationFailed // t_Validating_to_ValidationError
  some t: Transition | t.from = Validating and t.to = Computing and t.event = ValidationPassed // t_Validating_to_Computing
  some t: Transition | t.from = Computing and t.to = Saving and t.event = ComputationComplete // t_Computing_to_Saving
  some t: Transition | t.from = Processing and t.to = Ready and t.event = ProcessComplete // t_Processing_to_Ready
  some t: Transition | t.from = Processing and t.to = ErrorState and t.event = CriticalError // t_Processing_to_ErrorState
  some t: Transition | t.from = Initializing and t.to = Ready and t.event = InitComplete // t_Initializing_to_Ready
  some t: Transition | t.from = Ready and t.to = Processing and t.event = Start // t_Ready_to_Processing
  some t: Transition | t.from = ValidationError and t.to = Validating and t.event = Retry // t_ValidationError_to_Validating
  some t: Transition | t.from = ErrorState and t.to = Ready and t.event = ErrorRecovered // t_ErrorState_to_Ready
}

// Predicates for Analysis

pred Reachable[s1, s2: State] {
  s2 in s1.^(transitions.to)
}

pred WellFormed {
  // At least one initial state
  some StateMachine.initialStates

  // No orphaned states (except final states)
  all s: State - StateMachine.finalStates |
    some s.transitions or s in StateMachine.transitions.to

  // All states reachable from initial states
  all s: State | some init: StateMachine.initialStates |
    s = init or Reachable[init, s]
}

pred Deterministic {
  // No two transitions from same state with same event
  all s: State, e: Event |
    lone t: s.transitions | t.event = e
}

pred DeadlockFree {
  // All non-final states have outgoing transitions
  all s: State - StateMachine.finalStates |
    some s.transitions
}

// Behavioral Predicates

pred LivenessProperty {
  // From any initial state, a final state is reachable
  all init: StateMachine.initialStates |
    some final: StateMachine.finalStates |
      final = init or Reachable[init, final]
}

pred SafetyProperty {
  // No transition leads to an undefined state
  all t: Transition | t.to in StateMachine.states
}

// Assertions for Verification

// Check that well-formed state machines are deterministic
assert WellFormedImpliesDeterministic {
  WellFormed implies Deterministic
}

// Check that deterministic state machines are deadlock-free
assert DeterministicImpliesDeadlockFree {
  Deterministic implies DeadlockFree
}

// Check liveness property
assert LivenessHolds {
  WellFormed implies LivenessProperty
}

// Run Commands for Analysis

// Find a well-formed state machine instance
run WellFormed for 10 State, 8 Event, 15 Transition

// Find a deterministic state machine
run { WellFormed and Deterministic } for 10 State, 8 Event, 15 Transition

// Check assertions
check WellFormedImpliesDeterministic for 10 State, 8 Event, 15 Transition
check DeterministicImpliesDeadlockFree for 10 State, 8 Event, 15 Transition
check LivenessHolds for 10 State, 8 Event, 15 Transition
