(*
 * Generated TLA+/PlusCal FSM model for state machine: parsed_machine
 * Generated by upml-rs
 *)

---- MODULE parsed_machine ----
EXTENDS Naturals, Sequences, TLC

\* Constants
CONSTANTS
    Computing,
    ErrorState,
    Initializing,
    Processing,
    Ready,
    Saving,
    Validating,
    ValidationError

CONSTANTS
    ComputationComplete,
    CriticalError,
    EnterState,
    ErrorRecovered,
    ExitState,
    InitComplete,
    NullEvent,
    ProcessComplete,
    Retry,
    SaveComplete,
    Shutdown,
    Start,
    SystemShutdown,
    ValidationFailed,
    ValidationPassed

\* Variables
VARIABLES
    currentState,    \* Current state of the state machine
    eventQueue,      \* Queue of pending events
    inTransition     \* Flag indicating if a transition is in progress

\* Type invariants
States == {Computing, ErrorState, Initializing, Processing, Ready, Saving, Validating, ValidationError, "FINAL"}
Events == {ComputationComplete, CriticalError, EnterState, ErrorRecovered, ExitState, InitComplete, NullEvent, ProcessComplete, Retry, SaveComplete, Shutdown, Start, SystemShutdown, ValidationFailed, ValidationPassed}

TypeInvariant ==
    /\ currentState \in States
    /\ eventQueue \in Seq(Events)
    /\ inTransition \in BOOLEAN

\* Initial state predicate
Init ==
    /\ currentState = Validating
    /\ eventQueue = <<>>
    /\ inTransition = FALSE

\* Transition actions
\* Transition from Validating to ValidationError on ValidationFailed
Transition_Validating_ValidationError ==
    /\ currentState = Validating
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = ValidationFailed
    /\ inTransition = FALSE
    /\ currentState' = ValidationError
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Validating to Computing on ValidationPassed
Transition_Validating_Computing ==
    /\ currentState = Validating
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = ValidationPassed
    /\ inTransition = FALSE
    /\ currentState' = Computing
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Computing to Saving on ComputationComplete
Transition_Computing_Saving ==
    /\ currentState = Computing
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = ComputationComplete
    /\ inTransition = FALSE
    /\ currentState' = Saving
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Processing to Ready on ProcessComplete
Transition_Processing_Ready ==
    /\ currentState = Processing
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = ProcessComplete
    /\ inTransition = FALSE
    /\ currentState' = Ready
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Processing to ErrorState on CriticalError
Transition_Processing_ErrorState ==
    /\ currentState = Processing
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = CriticalError
    /\ inTransition = FALSE
    /\ currentState' = ErrorState
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Initializing to Ready on InitComplete
Transition_Initializing_Ready ==
    /\ currentState = Initializing
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = InitComplete
    /\ inTransition = FALSE
    /\ currentState' = Ready
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Ready to [*] on SystemShutdown
Transition_Ready_Final ==
    /\ currentState = Ready
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = SystemShutdown
    /\ inTransition = FALSE
    /\ currentState' = "FINAL"
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Ready to Processing on Start
Transition_Ready_Processing ==
    /\ currentState = Ready
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Start
    /\ inTransition = FALSE
    /\ currentState' = Processing
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from Saving to [*] on SaveComplete
Transition_Saving_Final ==
    /\ currentState = Saving
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = SaveComplete
    /\ inTransition = FALSE
    /\ currentState' = "FINAL"
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from ValidationError to Validating on Retry
Transition_ValidationError_Validating ==
    /\ currentState = ValidationError
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Retry
    /\ inTransition = FALSE
    /\ currentState' = Validating
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from ErrorState to Ready on ErrorRecovered
Transition_ErrorState_Ready ==
    /\ currentState = ErrorState
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = ErrorRecovered
    /\ inTransition = FALSE
    /\ currentState' = Ready
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE

\* Transition from ErrorState to [*] on Shutdown
Transition_ErrorState_Final ==
    /\ currentState = ErrorState
    /\ eventQueue # <<>> 
    /\ Head(eventQueue) = Shutdown
    /\ inTransition = FALSE
    /\ currentState' = "FINAL"
    /\ eventQueue' = Tail(eventQueue)
    /\ inTransition' = TRUE


\* Next state relation
Next ==
    \/ Transition_Validating_ValidationError
    \/ Transition_Validating_Computing
    \/ Transition_Computing_Saving
    \/ Transition_Processing_Ready
    \/ Transition_Processing_ErrorState
    \/ Transition_Initializing_Ready
    \/ Transition_Ready_Final
    \/ Transition_Ready_Processing
    \/ Transition_Saving_Final
    \/ Transition_ValidationError_Validating
    \/ Transition_ErrorState_Ready
    \/ Transition_ErrorState_Final
    \/ UNCHANGED <<currentState, eventQueue, inTransition>>

\* Specification
Spec == Init /\ [][Next]_<<currentState, eventQueue, inTransition>>

\* Properties
THEOREM Spec => []TypeInvariant

\* Liveness: eventually reach a final state
Liveness == <>( currentState = ErrorState \/ currentState = Saving \/ currentState = Ready )
THEOREM Spec => Liveness

\* Safety: always in a valid state
Safety == [](currentState \in States)
THEOREM Spec => Safety
====
