use std::io::Write;

use crate::state_machine::StateMachine;
use crate::Result;

/// Configuration for Alloy model generation
#[derive(Debug, Clone, Default)]
pub struct AlloyConfig {
    /// Maximum number of states to consider in analysis
    pub max_states: usize,
    /// Maximum number of events to consider
    pub max_events: usize,
    /// Maximum number of transitions
    pub max_transitions: usize,
    /// Generate structural constraints only (no behavioral analysis)
    pub structural_only: bool,
}

impl AlloyConfig {
    pub fn new() -> Self {
        Self {
            max_states: 10,
            max_events: 8,
            max_transitions: 15,
            structural_only: false,
        }
    }
}

/// Generate Alloy model for structural verification
pub fn generate_model<W: Write>(writer: W, state_machine: &StateMachine) -> Result<()> {
    generate_model_with_config(writer, state_machine, &AlloyConfig::new())
}

/// Generate Alloy model with custom configuration
pub fn generate_model_with_config<W: Write>(mut writer: W, state_machine: &StateMachine, config: &AlloyConfig) -> Result<()> {
    writeln!(writer, "// Generated Alloy model for state machine: {}", state_machine.id)?;
    writeln!(writer, "// Generated by upml-rs")?;
    writeln!(writer, "// Alloy structural verification model")?;
    writeln!(writer)?;

    // Generate basic signatures
    generate_signatures(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate facts (structural constraints)
    generate_facts(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate predicates for analysis
    generate_predicates(&mut writer, state_machine, config)?;
    writeln!(writer)?;

    // Generate assertions for verification
    generate_assertions(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate run commands
    generate_run_commands(&mut writer, config)?;

    Ok(())
}

/// Generate Alloy signatures (types)
fn generate_signatures<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "// Signatures (Types)")?;
    writeln!(writer)?;

    // Abstract state signature
    writeln!(writer, "abstract sig State {{")?;
    writeln!(writer, "  transitions: set Transition")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // Concrete state signatures
    let states = state_machine.states(false);
    for state in &states {
        let alloy_name = sanitize_alloy_name(state);
        writeln!(writer, "one sig {} extends State {{}} // {}", alloy_name, state)?;
    }
    writeln!(writer)?;

    // Event signature
    writeln!(writer, "abstract sig Event {{}}")?;
    let events = state_machine.events();
    for event in &events {
        if !event.starts_with("NullEvent") && !event.starts_with("EnterState") && !event.starts_with("ExitState") {
            let alloy_name = sanitize_alloy_name(event);
            writeln!(writer, "one sig {} extends Event {{}} // {}", alloy_name, event)?;
        }
    }
    writeln!(writer)?;

    // Transition signature
    writeln!(writer, "sig Transition {{")?;
    writeln!(writer, "  from: one State,")?;
    writeln!(writer, "  to: one State,")?;
    writeln!(writer, "  event: one Event,")?;
    writeln!(writer, "  guard: lone String,")?;
    writeln!(writer, "  effect: lone String")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // State machine signature
    writeln!(writer, "one sig StateMachine {{")?;
    writeln!(writer, "  states: set State,")?;
    writeln!(writer, "  initialStates: set State,")?;
    writeln!(writer, "  finalStates: set State,")?;
    writeln!(writer, "  transitions: set Transition")?;
    writeln!(writer, "}}")?;

    Ok(())
}

/// Generate facts (structural constraints)
fn generate_facts<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "// Facts (Structural Constraints)")?;
    writeln!(writer)?;

    // Basic structural constraints
    writeln!(writer, "fact StateMachineStructure {{")?;
    writeln!(writer, "  // All states belong to the state machine")?;
    writeln!(writer, "  StateMachine.states = State")?;
    writeln!(writer)?;

    writeln!(writer, "  // All transitions belong to the state machine")?;
    writeln!(writer, "  StateMachine.transitions = Transition")?;
    writeln!(writer)?;

    writeln!(writer, "  // Transitions are owned by their source states")?;
    writeln!(writer, "  all t: Transition | t in t.from.transitions")?;
    writeln!(writer)?;

    writeln!(writer, "  // Initial and final states are subsets of all states")?;
    writeln!(writer, "  StateMachine.initialStates in StateMachine.states")?;
    writeln!(writer, "  StateMachine.finalStates in StateMachine.states")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // Specific constraints based on the parsed state machine
    generate_specific_constraints(writer, state_machine)?;

    Ok(())
}

/// Generate specific constraints based on the parsed state machine
fn generate_specific_constraints<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "fact SpecificConstraints {{")?;

    // Define initial states
    let initial_states = state_machine.initial_states();
    if !initial_states.is_empty() {
        write!(writer, "  StateMachine.initialStates = ")?;
        for (i, state) in initial_states.iter().enumerate() {
            if i > 0 { write!(writer, " + ")?; }
            write!(writer, "{}", sanitize_alloy_name(state))?;
        }
        writeln!(writer)?;
    } else {
        writeln!(writer, "  no StateMachine.initialStates")?;
    }

    // Define final states
    let final_states = state_machine.final_states();
    if !final_states.is_empty() {
        write!(writer, "  StateMachine.finalStates = ")?;
        for (i, state) in final_states.iter().enumerate() {
            if i > 0 { write!(writer, " + ")?; }
            write!(writer, "{}", sanitize_alloy_name(state))?;
        }
        writeln!(writer)?;
    } else {
        writeln!(writer, "  no StateMachine.finalStates")?;
    }

    // Define specific transitions
    writeln!(writer)?;
    writeln!(writer, "  // Specific transitions from the state machine")?;
    for region in state_machine.regions.values() {
        for state in region.borrow().substates.values() {
            let state_borrow = state.borrow();
            for transition in state_borrow.transitions.values() {
                if transition.to_state != "[*]" {
                    writeln!(writer, "  some t: Transition | t.from = {} and t.to = {} and t.event = {} // {}",
                            sanitize_alloy_name(&transition.from_state),
                            sanitize_alloy_name(&transition.to_state),
                            sanitize_alloy_name(&transition.event),
                            transition.id)?;
                }
            }
        }
    }

    writeln!(writer, "}}")?;
    Ok(())
}

/// Generate predicates for analysis
fn generate_predicates<W: Write>(writer: &mut W, state_machine: &StateMachine, config: &AlloyConfig) -> Result<()> {
    writeln!(writer, "// Predicates for Analysis")?;
    writeln!(writer)?;

    // Reachability predicate
    writeln!(writer, "pred Reachable[s1, s2: State] {{")?;
    writeln!(writer, "  s2 in s1.^(transitions.to)")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // Well-formed state machine predicate
    writeln!(writer, "pred WellFormed {{")?;
    writeln!(writer, "  // At least one initial state")?;
    writeln!(writer, "  some StateMachine.initialStates")?;
    writeln!(writer)?;
    writeln!(writer, "  // No orphaned states (except final states)")?;
    writeln!(writer, "  all s: State - StateMachine.finalStates |")?;
    writeln!(writer, "    some s.transitions or s in StateMachine.transitions.to")?;
    writeln!(writer)?;
    writeln!(writer, "  // All states reachable from initial states")?;
    writeln!(writer, "  all s: State | some init: StateMachine.initialStates |")?;
    writeln!(writer, "    s = init or Reachable[init, s]")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // Deterministic predicate
    writeln!(writer, "pred Deterministic {{")?;
    writeln!(writer, "  // No two transitions from same state with same event")?;
    writeln!(writer, "  all s: State, e: Event |")?;
    writeln!(writer, "    lone t: s.transitions | t.event = e")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // Deadlock-free predicate
    writeln!(writer, "pred DeadlockFree {{")?;
    writeln!(writer, "  // All non-final states have outgoing transitions")?;
    writeln!(writer, "  all s: State - StateMachine.finalStates |")?;
    writeln!(writer, "    some s.transitions")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    if !config.structural_only {
        // Behavioral predicates
        generate_behavioral_predicates(writer, state_machine)?;
    }

    Ok(())
}

/// Generate behavioral predicates
fn generate_behavioral_predicates<W: Write>(writer: &mut W, _state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "// Behavioral Predicates")?;
    writeln!(writer)?;

    // Liveness predicate
    writeln!(writer, "pred LivenessProperty {{")?;
    writeln!(writer, "  // From any initial state, a final state is reachable")?;
    writeln!(writer, "  all init: StateMachine.initialStates |")?;
    writeln!(writer, "    some final: StateMachine.finalStates |")?;
    writeln!(writer, "      final = init or Reachable[init, final]")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    // Safety predicate
    writeln!(writer, "pred SafetyProperty {{")?;
    writeln!(writer, "  // No transition leads to an undefined state")?;
    writeln!(writer, "  all t: Transition | t.to in StateMachine.states")?;
    writeln!(writer, "}}")?;

    Ok(())
}

/// Generate assertions for verification
fn generate_assertions<W: Write>(writer: &mut W, _state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "// Assertions for Verification")?;
    writeln!(writer)?;

    writeln!(writer, "// Check that well-formed state machines are deterministic")?;
    writeln!(writer, "assert WellFormedImpliesDeterministic {{")?;
    writeln!(writer, "  WellFormed implies Deterministic")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    writeln!(writer, "// Check that deterministic state machines are deadlock-free")?;
    writeln!(writer, "assert DeterministicImpliesDeadlockFree {{")?;
    writeln!(writer, "  Deterministic implies DeadlockFree")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;

    writeln!(writer, "// Check liveness property")?;
    writeln!(writer, "assert LivenessHolds {{")?;
    writeln!(writer, "  WellFormed implies LivenessProperty")?;
    writeln!(writer, "}}")?;

    Ok(())
}

/// Generate run commands for analysis
fn generate_run_commands<W: Write>(writer: &mut W, config: &AlloyConfig) -> Result<()> {
    writeln!(writer, "// Run Commands for Analysis")?;
    writeln!(writer)?;

    writeln!(writer, "// Find a well-formed state machine instance")?;
    writeln!(writer, "run WellFormed for {} State, {} Event, {} Transition", 
             config.max_states, config.max_events, config.max_transitions)?;
    writeln!(writer)?;

    writeln!(writer, "// Find a deterministic state machine")?;
    writeln!(writer, "run {{ WellFormed and Deterministic }} for {} State, {} Event, {} Transition", 
             config.max_states, config.max_events, config.max_transitions)?;
    writeln!(writer)?;

    writeln!(writer, "// Check assertions")?;
    writeln!(writer, "check WellFormedImpliesDeterministic for {} State, {} Event, {} Transition", 
             config.max_states, config.max_events, config.max_transitions)?;
    writeln!(writer, "check DeterministicImpliesDeadlockFree for {} State, {} Event, {} Transition", 
             config.max_states, config.max_events, config.max_transitions)?;
    writeln!(writer, "check LivenessHolds for {} State, {} Event, {} Transition", 
             config.max_states, config.max_events, config.max_transitions)?;

    Ok(())
}

/// Sanitize identifier for Alloy (must start with letter, contain only alphanumeric and underscore)
fn sanitize_alloy_name(name: &str) -> String {
    let mut result = String::new();
    let mut first_char = true;
    
    for c in name.chars() {
        if first_char {
            if c.is_alphabetic() {
                result.push(c);
            } else {
                result.push('S'); // Start with 'S' for State/Signal
                if c.is_alphanumeric() {
                    result.push(c);
                } else {
                    result.push('_');
                }
            }
            first_char = false;
        } else {
            if c.is_alphanumeric() {
                result.push(c);
            } else {
                result.push('_');
            }
        }
    }
    
    // Ensure the result is not empty and not a reserved word
    if result.is_empty() {
        result = "State0".to_string();
    }
    
    // Avoid Alloy reserved words
    match result.as_str() {
        "sig" | "pred" | "fun" | "fact" | "assert" | "run" | "check" | "let" | "all" | "some" | "no" | "lone" | "one" | "set" => {
            format!("{}_", result)
        }
        _ => result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_machine::StateMachine;
    use std::rc::Rc;
    use std::cell::RefCell;

    #[test]
    fn test_generate_simple_alloy() {
        let mut state_machine = StateMachine::new("test".to_string());
        
        // Create a simple state machine for testing
        let region = Rc::new(RefCell::new(crate::state_machine::Region::new("main".to_string())));
        
        // Add states
        let state1 = Rc::new(RefCell::new(crate::state_machine::State::new("State1".to_string())));
        state1.borrow_mut().is_initial = true;
        
        let state2 = Rc::new(RefCell::new(crate::state_machine::State::new("State2".to_string())));
        state2.borrow_mut().is_final = true;
        
        // Add transition
        let transition = crate::state_machine::Transition {
            id: "t1".to_string(),
            from_state: "State1".to_string(),
            to_state: "State2".to_string(),
            event: "Event1".to_string(),
            guard: vec![],
            effect: vec![],
            location: Default::default(),
        };
        
        state1.borrow_mut().transitions.insert("t1".to_string(), transition);
        
        region.borrow_mut().substates.insert("State1".to_string(), state1);
        region.borrow_mut().substates.insert("State2".to_string(), state2);
        
        state_machine.regions.insert("main".to_string(), region);
        
        // Generate Alloy model
        let mut output = Vec::new();
        generate_model(&mut output, &state_machine).expect("Generation failed");
        
        let result = String::from_utf8(output).expect("Invalid UTF-8");
        
        // Check that the output contains expected elements
        assert!(result.contains("sig State"));
        assert!(result.contains("sig Event"));
        assert!(result.contains("sig Transition"));
        assert!(result.contains("one sig StateMachine"));
        assert!(result.contains("pred WellFormed"));
        assert!(result.contains("run WellFormed"));
    }

    #[test]
    fn test_sanitize_alloy_name() {
        assert_eq!(sanitize_alloy_name("ValidName"), "ValidName");
        assert_eq!(sanitize_alloy_name("Invalid-Name"), "Invalid_Name");
        assert_eq!(sanitize_alloy_name("123Invalid"), "S123Invalid");
        assert_eq!(sanitize_alloy_name("sig"), "sig_");
        assert_eq!(sanitize_alloy_name(""), "State0");
        assert_eq!(sanitize_alloy_name("[*]"), "S___");
    }

    #[test]
    fn test_generate_alloy_with_config() {
        let state_machine = StateMachine::new("test".to_string());
        
        let config = AlloyConfig {
            max_states: 5,
            max_events: 3,
            max_transitions: 8,
            structural_only: true,
        };
        
        let mut output = Vec::new();
        generate_model_with_config(&mut output, &state_machine, &config).expect("Generation failed");
        
        let result = String::from_utf8(output).expect("Invalid UTF-8");
        
        // Check that configuration is applied
        assert!(result.contains("for 5 State, 3 Event, 8 Transition"));
        // Should not contain behavioral predicates in structural_only mode
        assert!(!result.contains("// Behavioral Predicates"));
    }
}