use std::io::Write;

use crate::state_machine::StateMachine;
use crate::Result;

/// Configuration for NuSMV model generation
#[derive(Debug, Clone, Default)]
pub struct NuSMVConfig {
    /// Custom CTL/LTL properties to add to the model
    pub custom_properties: Vec<String>,
    /// Enable fairness constraints
    pub enable_fairness: bool,
    /// Generate only basic properties (skip advanced analysis)
    pub basic_properties_only: bool,
}

/// Generate NuSMV model for state machine verification
pub fn generate_model<W: Write>(writer: W, state_machine: &StateMachine) -> Result<()> {
    generate_model_with_config(writer, state_machine, &NuSMVConfig::default())
}

/// Generate NuSMV model with custom configuration
pub fn generate_model_with_config<W: Write>(mut writer: W, state_machine: &StateMachine, config: &NuSMVConfig) -> Result<()> {
    writeln!(writer, "-- Generated NuSMV model for state machine: {}", state_machine.id)?;
    writeln!(writer, "-- Generated by upml-rs")?;
    writeln!(writer, "-- NuSMV symbolic model checker format")?;
    writeln!(writer)?;

    // Generate main module
    generate_main_module(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate fairness constraints if enabled
    if config.enable_fairness {
        generate_fairness_constraints(&mut writer, state_machine)?;
        writeln!(writer)?;
    }

    // Generate temporal logic specifications
    generate_specifications(&mut writer, state_machine, config)?;

    // Generate custom properties if provided
    if !config.custom_properties.is_empty() {
        generate_custom_properties(&mut writer, &config.custom_properties)?;
    }

    Ok(())
}

/// Generate the main MODULE definition
fn generate_main_module<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "MODULE main")?;
    writeln!(writer)?;

    // Generate variable declarations
    generate_variables(writer, state_machine)?;
    writeln!(writer)?;

    // Generate ASSIGN section
    generate_assignments(writer, state_machine)?;
    writeln!(writer)?;

    Ok(())
}

/// Generate variable declarations (VAR section)
fn generate_variables<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "VAR")?;
    
    // Current state variable
    let states = state_machine.states(false);
    if !states.is_empty() {
        write!(writer, "  state : {{")?;
        let state_list: Vec<String> = states.into_iter().collect();
        for (i, state) in state_list.iter().enumerate() {
            if i > 0 { write!(writer, ", ")?; }
            write!(writer, "{}", sanitize_identifier(state))?;
        }
        writeln!(writer, "}};")?;
    }

    // Event variable (input)
    let events = state_machine.events();
    if !events.is_empty() {
        write!(writer, "  event : {{")?;
        let event_list: Vec<String> = events.into_iter().collect();
        for (i, event) in event_list.iter().enumerate() {
            if i > 0 { write!(writer, ", ")?; }
            write!(writer, "{}", sanitize_identifier(&event))?;
        }
        writeln!(writer, "}};")?;
    }

    Ok(())
}

/// Generate ASSIGN section with transition logic
fn generate_assignments<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "ASSIGN")?;
    
    // Initial state assignment
    let initial_states = state_machine.initial_states();
    if !initial_states.is_empty() {
        write!(writer, "  init(state) := ")?;
        if initial_states.len() == 1 {
            writeln!(writer, "{};", sanitize_identifier(initial_states.iter().next().unwrap()))?;
        } else {
            // Multiple initial states - use non-deterministic choice
            write!(writer, "{{")?;
            for (i, state) in initial_states.iter().enumerate() {
                if i > 0 { write!(writer, ", ")?; }
                write!(writer, "{}", sanitize_identifier(state))?;
            }
            writeln!(writer, "}};")?;
        }
    }

    // Next state transitions
    writeln!(writer, "  next(state) := case")?;
    
    // Generate transitions for each state
    for region in state_machine.regions.values() {
        for state in region.borrow().substates.values() {
            let state_borrow = state.borrow();
            
            for transition in state_borrow.transitions.values() {
                // Handle special [*] states
                let from_state = if transition.from_state == "[*]" {
                    continue; // Skip initial transitions, handled above
                } else {
                    sanitize_identifier(&transition.from_state)
                };
                
                let to_state = if transition.to_state == "[*]" {
                    // For transitions to final state, mark the from_state as final
                    // and keep it in the same state (self-loop)
                    sanitize_identifier(&transition.from_state)
                } else {
                    sanitize_identifier(&transition.to_state)
                };

                let event = sanitize_identifier(&transition.event);
                
                // Generate condition and guard
                write!(writer, "    state = {} & event = {}", from_state, event)?;
                
                // Add guard condition if present
                if !transition.guard.is_empty() {
                    write!(writer, " & ({})", format_guard(&transition.guard))?;
                }
                
                writeln!(writer, " : {};", to_state)?;
            }
        }
    }
    
    // Default case - state remains unchanged
    writeln!(writer, "    TRUE : state;")?;
    writeln!(writer, "  esac;")?;

    Ok(())
}

/// Generate fairness constraints
fn generate_fairness_constraints<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "-- Fairness Constraints")?;
    writeln!(writer, "-- These constraints ensure fair execution paths")?;
    
    let events = state_machine.events();
    let states = state_machine.states(false);
    let final_states = state_machine.final_states();
    
    // Fairness constraint: each meaningful event should be eventually possible
    // In NuSMV, FAIRNESS expects a boolean expression that should be true infinitely often
    for event in &events {
        if !event.starts_with("NullEvent") && !event.starts_with("EnterState") && !event.starts_with("ExitState") {
            writeln!(writer, "FAIRNESS event = {} -- Event {} should be eventually possible", 
                    sanitize_identifier(event), event)?;
        }
    }
    
    // Fairness constraint: progress from non-final states
    // In NuSMV, fairness constraints should be simple boolean expressions
    // We ensure that transitions are taken fairly by constraining events
    for state in &states {
        let has_outgoing = has_outgoing_transitions(state_machine, state);
        if has_outgoing && !final_states.contains(state) {
            // Find events that can cause transitions from this state
            let outgoing_events = get_outgoing_events(state_machine, state);
            if !outgoing_events.is_empty() {
                for event in outgoing_events {
                    writeln!(writer, "FAIRNESS !(state = {} & event = {}) -- Fair transition from {} on {}", 
                            sanitize_identifier(state), sanitize_identifier(&event), state, event)?;
                }
            }
        }
    }
    
    writeln!(writer)?;
    Ok(())
}

/// Generate temporal logic specifications
fn generate_specifications<W: Write>(writer: &mut W, state_machine: &StateMachine, config: &NuSMVConfig) -> Result<()> {
    writeln!(writer, "-- Temporal Logic Specifications")?;
    writeln!(writer)?;

    // Basic reachability properties
    generate_reachability_specs(writer, state_machine)?;
    
    // Safety properties
    generate_safety_specs(writer, state_machine)?;
    
    // Liveness properties
    generate_liveness_specs(writer, state_machine)?;
    
    // Advanced properties (only if not basic mode)
    if !config.basic_properties_only {
        generate_advanced_properties(writer, state_machine)?;
    }

    Ok(())
}

/// Generate custom user-defined properties
fn generate_custom_properties<W: Write>(writer: &mut W, custom_properties: &[String]) -> Result<()> {
    writeln!(writer, "-- Custom User-Defined Properties")?;
    
    for (i, property) in custom_properties.iter().enumerate() {
        writeln!(writer, "SPEC {} -- Custom property {}", property, i + 1)?;
    }
    
    writeln!(writer)?;
    Ok(())
}

/// Generate advanced temporal logic properties
fn generate_advanced_properties<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "-- Advanced Properties")?;
    
    let states = state_machine.states(false);
    let initial_states = state_machine.initial_states();
    let final_states = state_machine.final_states();
    
    // Mutual exclusion: only one state is active at a time (already guaranteed by design)
    writeln!(writer, "-- State mutual exclusion is guaranteed by design")?;
    
    // Reachability from any reachable state to final states
    if !final_states.is_empty() {
        for state in &states {
            if !final_states.contains(state) && !initial_states.contains(state) {
                write!(writer, "SPEC AG (state = {} -> EF (", sanitize_identifier(state))?;
                for (i, final_state) in final_states.iter().enumerate() {
                    if i > 0 { write!(writer, " | ")?; }
                    write!(writer, "state = {}", sanitize_identifier(final_state))?;
                }
                writeln!(writer, ")) -- From {} can reach final states", state)?;
            }
        }
    }
    
    // Determinism check: if multiple transitions exist, they should be mutually exclusive
    generate_determinism_properties(writer, state_machine)?;
    
    writeln!(writer)?;
    Ok(())
}

/// Generate determinism properties
fn generate_determinism_properties<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "-- Determinism Properties")?;
    
    // Check for states with multiple outgoing transitions on the same event
    for region in state_machine.regions.values() {
        for state in region.borrow().substates.values() {
            let state_borrow = state.borrow();
            let mut event_transitions: std::collections::HashMap<String, Vec<String>> = std::collections::HashMap::new();
            
            for transition in state_borrow.transitions.values() {
                event_transitions.entry(transition.event.clone())
                    .or_insert_with(Vec::new)
                    .push(transition.to_state.clone());
            }
            
            for (event, targets) in event_transitions {
                if targets.len() > 1 {
                    // Generate property to ensure mutual exclusion of guards
                    writeln!(writer, "-- Non-deterministic transition from {} on {} to {:?}", 
                            state_borrow.id, event, targets)?;
                    writeln!(writer, "-- Guards should be mutually exclusive")?;
                }
            }
        }
    }
    
    Ok(())
}

/// Check if a state has outgoing transitions
fn has_outgoing_transitions(state_machine: &StateMachine, state_id: &str) -> bool {
    for region in state_machine.regions.values() {
        if let Some(state) = region.borrow().substates.get(state_id) {
            return !state.borrow().transitions.is_empty();
        }
    }
    false
}

/// Get events that can cause transitions from a specific state
fn get_outgoing_events(state_machine: &StateMachine, state_id: &str) -> Vec<String> {
    let mut events = Vec::new();
    for region in state_machine.regions.values() {
        if let Some(state) = region.borrow().substates.get(state_id) {
            for transition in state.borrow().transitions.values() {
                if !events.contains(&transition.event) {
                    events.push(transition.event.clone());
                }
            }
        }
    }
    events
}

/// Generate reachability specifications
fn generate_reachability_specs<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "-- Reachability Properties")?;
    
    let states = state_machine.states(false);
    let initial_states = state_machine.initial_states();
    let final_states = state_machine.final_states();
    
    // All non-initial states should be reachable from initial states
    for state in &states {
        if !initial_states.contains(state) {
            writeln!(writer, "SPEC EF (state = {}) -- {} should be reachable", 
                    sanitize_identifier(state), state)?;
        }
    }
    
    // Add comment about final states if any exist
    if !final_states.is_empty() {
        writeln!(writer, "-- Final states: {:?}", final_states)?;
    }
    
    writeln!(writer)?;
    Ok(())
}

/// Generate safety specifications
fn generate_safety_specs<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "-- Safety Properties")?;
    
    // No deadlocks - from any non-final state, some transition should be possible
    let final_states = state_machine.final_states();
    let states = state_machine.states(false);
    
    for state in &states {
        if !final_states.contains(state) {
            // Find if this state has outgoing transitions
            let mut has_transitions = false;
            for region in state_machine.regions.values() {
                if let Some(state_ref) = region.borrow().substates.get(state) {
                    if !state_ref.borrow().transitions.is_empty() {
                        has_transitions = true;
                        break;
                    }
                }
            }
            
            if has_transitions {
                writeln!(writer, "SPEC AG (state = {} -> EX TRUE) -- No deadlock from {}", 
                        sanitize_identifier(state), state)?;
            }
        }
    }
    
    writeln!(writer)?;
    Ok(())
}

/// Generate liveness specifications
fn generate_liveness_specs<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "-- Liveness Properties")?;
    
    let initial_states = state_machine.initial_states();
    let final_states = state_machine.final_states();
    
    // From any initial state, a final state should eventually be reachable
    if !final_states.is_empty() {
        for initial_state in &initial_states {
            write!(writer, "SPEC AG (state = {} -> AF (", sanitize_identifier(initial_state))?;
            for (i, final_state) in final_states.iter().enumerate() {
                if i > 0 { write!(writer, " | ")?; }
                write!(writer, "state = {}", sanitize_identifier(final_state))?;
            }
            writeln!(writer, ")) -- From {} eventually reach final state", initial_state)?;
        }
    }
    
    writeln!(writer)?;
    Ok(())
}

/// Sanitize identifier for NuSMV (replace invalid characters)
fn sanitize_identifier(id: &str) -> String {
    id.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Format guard conditions for NuSMV
fn format_guard(guard: &[String]) -> String {
    if guard.is_empty() {
        "TRUE".to_string()
    } else {
        guard.join(" & ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_machine::StateMachine;
    use std::rc::Rc;
    use std::cell::RefCell;

    #[test]
    fn test_generate_simple_nusmv() {
        let mut state_machine = StateMachine::new("test".to_string());
        
        // Create a simple state machine for testing
        let region = Rc::new(RefCell::new(crate::state_machine::Region::new("main".to_string())));
        
        // Add states
        let state1 = Rc::new(RefCell::new(crate::state_machine::State::new("State1".to_string())));
        state1.borrow_mut().is_initial = true;
        
        let state2 = Rc::new(RefCell::new(crate::state_machine::State::new("State2".to_string())));
        state2.borrow_mut().is_final = true;
        
        // Add transition
        let transition = crate::state_machine::Transition {
            id: "t1".to_string(),
            from_state: "State1".to_string(),
            to_state: "State2".to_string(),
            event: "Event1".to_string(),
            guard: vec![],
            effect: vec![],
            location: Default::default(),
        };
        
        state1.borrow_mut().transitions.insert("t1".to_string(), transition);
        
        region.borrow_mut().substates.insert("State1".to_string(), state1);
        region.borrow_mut().substates.insert("State2".to_string(), state2);
        
        state_machine.regions.insert("main".to_string(), region);
        
        // Generate NuSMV model
        let mut output = Vec::new();
        generate_model(&mut output, &state_machine).expect("Generation failed");
        
        let result = String::from_utf8(output).expect("Invalid UTF-8");
        
        // Check that the output contains expected elements
        assert!(result.contains("MODULE main"));
        assert!(result.contains("VAR"));
        // The order of states in HashSet is not guaranteed, so check both states separately
        assert!(result.contains("State1") && result.contains("State2"));
        assert!(result.contains("ASSIGN"));
        assert!(result.contains("init(state) := State1"));
        assert!(result.contains("SPEC"));
    }

    #[test]
    fn test_generate_nusmv_with_fairness() {
        let mut state_machine = StateMachine::new("test".to_string());
        
        // Create a simple state machine
        let region = Rc::new(RefCell::new(crate::state_machine::Region::new("main".to_string())));
        let state1 = Rc::new(RefCell::new(crate::state_machine::State::new("State1".to_string())));
        state1.borrow_mut().is_initial = true;
        
        let transition = crate::state_machine::Transition {
            id: "t1".to_string(),
            from_state: "State1".to_string(),
            to_state: "State1".to_string(),
            event: "Event1".to_string(),
            guard: vec![],
            effect: vec![],
            location: Default::default(),
        };
        
        state1.borrow_mut().transitions.insert("t1".to_string(), transition);
        region.borrow_mut().substates.insert("State1".to_string(), state1);
        state_machine.regions.insert("main".to_string(), region);
        
        // Generate with fairness constraints
        let config = NuSMVConfig {
            enable_fairness: true,
            ..Default::default()
        };
        
        let mut output = Vec::new();
        generate_model_with_config(&mut output, &state_machine, &config).expect("Generation failed");
        
        let result = String::from_utf8(output).expect("Invalid UTF-8");
        
        // Check that fairness constraints are present
        assert!(result.contains("FAIRNESS"));
        assert!(result.contains("-- Fairness Constraints"));
    }

    #[test]
    fn test_generate_nusmv_with_custom_properties() {
        let state_machine = StateMachine::new("test".to_string());
        
        let config = NuSMVConfig {
            custom_properties: vec![
                "AG (state != ErrorState)".to_string(),
                "EF (state = TargetState)".to_string(),
            ],
            ..Default::default()
        };
        
        let mut output = Vec::new();
        generate_model_with_config(&mut output, &state_machine, &config).expect("Generation failed");
        
        let result = String::from_utf8(output).expect("Invalid UTF-8");
        
        // Check that custom properties are present
        assert!(result.contains("-- Custom User-Defined Properties"));
        assert!(result.contains("AG (state != ErrorState)"));
        assert!(result.contains("EF (state = TargetState)"));
    }

    #[test]
    fn test_sanitize_identifier() {
        assert_eq!(sanitize_identifier("Valid_Name"), "Valid_Name");
        assert_eq!(sanitize_identifier("Invalid-Name"), "Invalid_Name");
        assert_eq!(sanitize_identifier("Name with spaces"), "Name_with_spaces");
        assert_eq!(sanitize_identifier("[*]"), "");
    }
}