use std::io::Write;
use crate::state_machine::StateMachine;
use crate::Result;

/// Generate Promela code for FSM (Finite State Machine)
pub fn generate_fsm<W: Write>(mut writer: W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/*")?;
    writeln!(writer, " * Generated Promela FSM model for state machine: {}", state_machine.id)?;
    writeln!(writer, " * Generated by upml-rs")?;
    writeln!(writer, " */")?;
    writeln!(writer)?;

    // Generate message types (events)
    generate_message_types(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate state enumeration
    generate_state_enum(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate global variables
    generate_global_variables(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate main process
    generate_main_process(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate LTL properties if any
    generate_ltl_properties(&mut writer, state_machine)?;

    Ok(())
}

/// Generate Promela code for HSM (Hierarchical State Machine)
pub fn generate_hsm<W: Write>(mut writer: W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/*")?;
    writeln!(writer, " * Generated Promela HSM model for state machine: {}", state_machine.id)?;
    writeln!(writer, " * Generated by upml-rs")?;
    writeln!(writer, " */")?;
    writeln!(writer)?;

    // Generate message types (events)
    generate_message_types(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate state enumeration (hierarchical)
    generate_hierarchical_state_enum(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate global variables for HSM
    generate_hsm_global_variables(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate HSM main process
    generate_hsm_main_process(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate LTL properties if any
    generate_ltl_properties(&mut writer, state_machine)?;

    Ok(())
}

fn generate_message_types<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* Message types (events) */")?;
    writeln!(writer, "mtype = {{")?;
    
    let events = state_machine.events();
    let mut event_list: Vec<_> = events.into_iter().collect();
    event_list.sort();
    
    for (i, event) in event_list.iter().enumerate() {
        if i == event_list.len() - 1 {
            writeln!(writer, "    {}", event)?;
        } else {
            writeln!(writer, "    {},", event)?;
        }
    }
    
    writeln!(writer, "}};")?;
    Ok(())
}

fn generate_state_enum<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* State enumeration */")?;
    writeln!(writer, "mtype = {{")?;
    
    let states = state_machine.states(false);
    let mut state_list: Vec<_> = states.into_iter().collect();
    state_list.sort();
    
    for (i, state) in state_list.iter().enumerate() {
        if i == state_list.len() - 1 {
            writeln!(writer, "    state_{}", state)?;
        } else {
            writeln!(writer, "    state_{},", state)?;
        }
    }
    
    writeln!(writer, "}};")?;
    Ok(())
}

fn generate_hierarchical_state_enum<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* Hierarchical state enumeration */")?;
    writeln!(writer, "mtype = {{")?;
    
    let states = state_machine.states(true);
    let mut state_list: Vec<_> = states.into_iter().collect();
    state_list.sort();
    
    for (i, state) in state_list.iter().enumerate() {
        if i == state_list.len() - 1 {
            writeln!(writer, "    state_{}", state)?;
        } else {
            writeln!(writer, "    state_{},", state)?;
        }
    }
    
    writeln!(writer, "}};")?;
    Ok(())
}

fn generate_global_variables<W: Write>(writer: &mut W, _state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* Global variables */")?;
    writeln!(writer, "mtype currentState;")?;
    writeln!(writer, "chan eventQueue = [16] of {{ mtype }};")?;
    writeln!(writer, "bool inTransition = false;")?;
    
    // Add any global variables from state configurations
    // This would be extracted from the original C++ parsing
    
    Ok(())
}

fn generate_hsm_global_variables<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* HSM Global variables */")?;
    writeln!(writer, "mtype currentState;")?;
    writeln!(writer, "mtype stateStack[{}];", state_machine.depth())?;
    writeln!(writer, "byte stackDepth = 0;")?;
    writeln!(writer, "chan eventQueue = [16] of {{ mtype }};")?;
    writeln!(writer, "bool inTransition = false;")?;
    
    Ok(())
}

fn generate_main_process<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* Main FSM process */")?;
    writeln!(writer, "active proctype StateMachine() {{")?;
    
    // Initialize to initial state
    let initial_states = state_machine.initial_states();
    if let Some(initial_state) = initial_states.iter().next() {
        writeln!(writer, "    currentState = state_{}; ", initial_state)?;
    }
    
    writeln!(writer, "    ")?;
    writeln!(writer, "    do")?;
    writeln!(writer, "    :: eventQueue?event ->")?;
    writeln!(writer, "        atomic {{")?;
    writeln!(writer, "            inTransition = true;")?;
    writeln!(writer, "            ")?;
    
    // Generate state transition logic
    generate_fsm_transitions(writer, state_machine)?;
    
    writeln!(writer, "            ")?;
    writeln!(writer, "            inTransition = false;")?;
    writeln!(writer, "        }}")?;
    writeln!(writer, "    od")?;
    writeln!(writer, "}}")?;
    
    Ok(())
}

fn generate_hsm_main_process<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* Main HSM process */")?;
    writeln!(writer, "active proctype HierarchicalStateMachine() {{")?;
    
    // Initialize to initial state
    let initial_states = state_machine.initial_states();
    if let Some(initial_state) = initial_states.iter().next() {
        writeln!(writer, "    currentState = state_{}; ", initial_state)?;
        writeln!(writer, "    stateStack[0] = currentState;")?;
        writeln!(writer, "    stackDepth = 1;")?;
    }
    
    writeln!(writer, "    ")?;
    writeln!(writer, "    do")?;
    writeln!(writer, "    :: eventQueue?event ->")?;
    writeln!(writer, "        atomic {{")?;
    writeln!(writer, "            inTransition = true;")?;
    writeln!(writer, "            ")?;
    
    // Generate hierarchical state transition logic
    generate_hsm_transitions(writer, state_machine)?;
    
    writeln!(writer, "            ")?;
    writeln!(writer, "            inTransition = false;")?;
    writeln!(writer, "        }}")?;
    writeln!(writer, "    od")?;
    writeln!(writer, "}}")?;
    
    Ok(())
}

fn generate_fsm_transitions<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "            /* State transitions */")?;
    
    for region in state_machine.regions.values() {
        generate_region_transitions(writer, &region.borrow(), false)?;
    }
    
    Ok(())
}

fn generate_hsm_transitions<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "            /* Hierarchical state transitions */")?;
    
    for region in state_machine.regions.values() {
        generate_region_transitions(writer, &region.borrow(), true)?;
    }
    
    Ok(())
}

fn generate_region_transitions<W: Write>(
    writer: &mut W, 
    region: &crate::state_machine::Region, 
    hierarchical: bool
) -> Result<()> {
    for state in region.substates.values() {
        let state_borrow = state.borrow();
        
        for transition in state_borrow.transitions.values() {
            writeln!(writer, "            if")?;
            writeln!(writer, "            :: (currentState == state_{} && event == {}) ->", 
                     transition.from_state, transition.event)?;
            
            // Generate guard condition if present
            if !transition.guard.is_empty() {
                writeln!(writer, "                if")?;
                for guard in &transition.guard {
                    writeln!(writer, "                :: ({}) ->", guard)?;
                }
            }
            
            // Generate transition effects
            for effect in &transition.effect {
                writeln!(writer, "                    /* Effect: {} */", effect)?;
                generate_effect_code(writer, effect)?;
            }
            
            // Change state
            writeln!(writer, "                    currentState = state_{};", transition.to_state)?;
            
            if !transition.guard.is_empty() {
                writeln!(writer, "                :: else -> skip")?;
                writeln!(writer, "                fi")?;
            }
            
            writeln!(writer, "            :: else -> skip")?;
            writeln!(writer, "            fi")?;
        }
        
        // Generate transitions for substates if hierarchical
        if hierarchical {
            for subregion in state_borrow.regions.values() {
                generate_region_transitions(writer, &subregion.borrow(), hierarchical)?;
            }
        }
    }
    
    Ok(())
}

fn generate_effect_code<W: Write>(writer: &mut W, effect: &str) -> Result<()> {
    // Parse and generate code for different types of effects
    if effect.starts_with("send event:") {
        // Parse send event statement
        if let Some(event_part) = effect.strip_prefix("send event:") {
            if let Some(event_name) = event_part.split(" to state:").next() {
                writeln!(writer, "                    eventQueue!{};", event_name)?;
            }
        }
    } else if effect.starts_with("trace ") {
        // Generate trace statement
        writeln!(writer, "                    printf(\"TRACE: {}\\n\");", effect)?;
    } else {
        // Generic assignment or statement
        writeln!(writer, "                    /* {} */", effect)?;
    }
    
    Ok(())
}

fn generate_ltl_properties<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "/* LTL Properties */")?;
    
    // Generate basic liveness property
    writeln!(writer, "/* Basic liveness: eventually reach a final state */")?;
    let final_states: Vec<_> = state_machine.states(true)
        .into_iter()
        .filter(|state_id| {
            if let Some(state) = state_machine.find_state(state_id) {
                state.borrow().is_final
            } else {
                false
            }
        })
        .collect();
    
    if !final_states.is_empty() {
        write!(writer, "ltl liveness {{ <>( ")?;
        for (i, state) in final_states.iter().enumerate() {
            if i > 0 {
                write!(writer, " || ")?;
            }
            write!(writer, "currentState == state_{}", state)?;
        }
        writeln!(writer, " ) }}")?;
    }
    
    // Generate safety property: no deadlock
    writeln!(writer, "ltl safety {{ [](!inTransition -> <>inTransition) }}")?;
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_machine::{StateMachineBuilder, Transition};
    use std::io::Cursor;

    #[test]
    fn test_generate_simple_fsm() {
        let sm = StateMachineBuilder::new("test_machine".to_string())
            .add_region("main_region".to_string())
                .add_state("state1".to_string())
                    .initial()
                    .add_transition(Transition::new(
                        "t1".to_string(),
                        "state1".to_string(),
                        "state2".to_string(),
                        "event1".to_string(),
                    ))
                    .finish_state()
                .add_state("state2".to_string())
                    .final_state()
                    .finish_state()
                .finish_region()
            .build();

        let mut output = Cursor::new(Vec::new());
        generate_fsm(&mut output, &sm).unwrap();
        
        let result = String::from_utf8(output.into_inner()).unwrap();
        assert!(result.contains("Generated Promela FSM model"));
        assert!(result.contains("state_state1"));
        assert!(result.contains("state_state2"));
        assert!(result.contains("event1"));
    }
}