use std::io::Write;
use crate::state_machine::StateMachine;
use crate::Result;

/// Generate TLA+/PlusCal code for FSM (Finite State Machine)
pub fn generate_fsm<W: Write>(mut writer: W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "(*")?;
    writeln!(writer, " * Generated TLA+/PlusCal FSM model for state machine: {}", state_machine.id)?;
    writeln!(writer, " * Generated by upml-rs")?;
    writeln!(writer, " *)")?;
    writeln!(writer)?;

    // Generate module header
    writeln!(writer, "---- MODULE {} ----", state_machine.id)?;
    writeln!(writer, "EXTENDS Naturals, Sequences, TLC")?;
    writeln!(writer)?;

    // Generate constants and variables
    generate_tla_constants(&mut writer, state_machine)?;
    writeln!(writer)?;
    
    generate_tla_variables(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate type invariants
    generate_type_invariants(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate initial state predicate
    generate_init_predicate(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate transition actions
    generate_transition_actions(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate next state relation
    generate_next_relation(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate specification
    generate_specification(&mut writer, state_machine)?;
    writeln!(writer)?;

    // Generate properties
    generate_tla_properties(&mut writer, state_machine)?;

    writeln!(writer, "====")?;

    Ok(())
}

fn generate_tla_constants<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Constants")?;
    
    // Generate state constants
    let states = state_machine.states(false);
    let mut state_list: Vec<_> = states.into_iter().collect();
    state_list.sort();
    
    writeln!(writer, "CONSTANTS")?;
    for (i, state) in state_list.iter().enumerate() {
        if i == state_list.len() - 1 {
            writeln!(writer, "    {}", state)?;
        } else {
            writeln!(writer, "    {},", state)?;
        }
    }
    writeln!(writer)?;
    
    // Generate event constants
    let events = state_machine.events();
    let mut event_list: Vec<_> = events.into_iter().collect();
    event_list.sort();
    
    writeln!(writer, "CONSTANTS")?;
    for (i, event) in event_list.iter().enumerate() {
        if i == event_list.len() - 1 {
            writeln!(writer, "    {}", event)?;
        } else {
            writeln!(writer, "    {},", event)?;
        }
    }
    
    Ok(())
}

fn generate_tla_variables<W: Write>(writer: &mut W, _state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Variables")?;
    writeln!(writer, "VARIABLES")?;
    writeln!(writer, "    currentState,    \\* Current state of the state machine")?;
    writeln!(writer, "    eventQueue,      \\* Queue of pending events")?;
    writeln!(writer, "    inTransition     \\* Flag indicating if a transition is in progress")?;
    
    Ok(())
}

fn generate_type_invariants<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Type invariants")?;
    
    let states = state_machine.states(false);
    let mut state_list: Vec<_> = states.into_iter().collect();
    state_list.sort();
    
    write!(writer, "States == {{")?;
    for (i, state) in state_list.iter().enumerate() {
        if i > 0 {
            write!(writer, ", ")?;
        }
        write!(writer, "{}", state)?;
    }
    // Add special FINAL state for transitions to [*]
    if !state_list.is_empty() {
        write!(writer, ", ")?;
    }
    write!(writer, "\"FINAL\"")?;
    writeln!(writer, "}}")?;
    
    let events = state_machine.events();
    let mut event_list: Vec<_> = events.into_iter().collect();
    event_list.sort();
    
    write!(writer, "Events == {{")?;
    for (i, event) in event_list.iter().enumerate() {
        if i > 0 {
            write!(writer, ", ")?;
        }
        write!(writer, "{}", event)?;
    }
    writeln!(writer, "}}")?;
    writeln!(writer)?;
    
    writeln!(writer, "TypeInvariant ==")?;
    writeln!(writer, "    /\\ currentState \\in States")?;
    writeln!(writer, "    /\\ eventQueue \\in Seq(Events)")?;
    writeln!(writer, "    /\\ inTransition \\in BOOLEAN")?;
    
    Ok(())
}

fn generate_init_predicate<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Initial state predicate")?;
    writeln!(writer, "Init ==")?;
    
    // Find initial state
    let initial_states = state_machine.initial_states();
    if let Some(initial_state) = initial_states.iter().next() {
        writeln!(writer, "    /\\ currentState = {}", initial_state)?;
    } else {
        writeln!(writer, "    /\\ currentState \\in States")?;
    }
    
    writeln!(writer, "    /\\ eventQueue = <<>>")?;
    writeln!(writer, "    /\\ inTransition = FALSE")?;
    
    Ok(())
}

fn generate_transition_actions<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Transition actions")?;
    
    for region in state_machine.regions.values() {
        generate_region_transition_actions(writer, &region.borrow())?;
    }
    
    Ok(())
}

fn generate_region_transition_actions<W: Write>(
    writer: &mut W, 
    region: &crate::state_machine::Region
) -> Result<()> {
    for state in region.substates.values() {
        let state_borrow = state.borrow();
        
        for transition in state_borrow.transitions.values() {
            writeln!(writer, "\\* Transition from {} to {} on {}", 
                     transition.from_state, transition.to_state, transition.event)?;
            let from_name = if transition.from_state == "[*]" { "Initial" } else { &transition.from_state };
            let to_name = if transition.to_state == "[*]" { "Final" } else { &transition.to_state };
            writeln!(writer, "Transition_{}_{} ==", from_name, to_name)?;
            writeln!(writer, "    /\\ currentState = {}", transition.from_state)?;
            writeln!(writer, "    /\\ eventQueue # <<>> ")?;
            writeln!(writer, "    /\\ Head(eventQueue) = {}", transition.event)?;
            writeln!(writer, "    /\\ inTransition = FALSE")?;
            
            // Generate guard conditions
            if !transition.guard.is_empty() {
                for guard in &transition.guard {
                    writeln!(writer, "    /\\ ({})", guard)?;
                }
            }
            
            // Generate state change and effects
            if transition.to_state == "[*]" {
                // Transition to final state - use a special final state constant
                writeln!(writer, "    /\\ currentState' = \"FINAL\"")?;
            } else {
                writeln!(writer, "    /\\ currentState' = {}", transition.to_state)?;
            }
            writeln!(writer, "    /\\ eventQueue' = Tail(eventQueue)")?;
            writeln!(writer, "    /\\ inTransition' = TRUE")?;
            
            // Generate effects as comments for now
            for effect in &transition.effect {
                writeln!(writer, "    \\* Effect: {}", effect)?;
            }
            
            writeln!(writer)?;
        }
        
        // Generate transitions for substates
        for subregion in state_borrow.regions.values() {
            generate_region_transition_actions(writer, &subregion.borrow())?;
        }
    }
    
    Ok(())
}

fn generate_next_relation<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Next state relation")?;
    writeln!(writer, "Next ==")?;
    
    let mut first = true;
    for region in state_machine.regions.values() {
        for state in region.borrow().substates.values() {
            let state_borrow = state.borrow();
            
            for transition in state_borrow.transitions.values() {
                let from_name = if transition.from_state == "[*]" { "Initial" } else { &transition.from_state };
                let to_name = if transition.to_state == "[*]" { "Final" } else { &transition.to_state };
                
                if first {
                    writeln!(writer, "    \\/ Transition_{}_{}", from_name, to_name)?;
                    first = false;
                } else {
                    writeln!(writer, "    \\/ Transition_{}_{}", from_name, to_name)?;
                }
            }
        }
    }
    
    // Add stuttering step
    writeln!(writer, "    \\/ UNCHANGED <<currentState, eventQueue, inTransition>>")?;
    
    Ok(())
}

fn generate_specification<W: Write>(writer: &mut W, _state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Specification")?;
    writeln!(writer, "Spec == Init /\\ [][Next]_<<currentState, eventQueue, inTransition>>")?;
    
    Ok(())
}

fn generate_tla_properties<W: Write>(writer: &mut W, state_machine: &StateMachine) -> Result<()> {
    writeln!(writer, "\\* Properties")?;
    
    // Generate type correctness property
    writeln!(writer, "THEOREM Spec => []TypeInvariant")?;
    writeln!(writer)?;
    
    // Generate liveness property for final states
    let final_states: Vec<_> = state_machine.states(true)
        .into_iter()
        .filter(|state_id| {
            if let Some(state) = state_machine.find_state(state_id) {
                state.borrow().is_final
            } else {
                false
            }
        })
        .collect();
    
    if !final_states.is_empty() {
        writeln!(writer, "\\* Liveness: eventually reach a final state")?;
        write!(writer, "Liveness == <>( ")?;
        for (i, state) in final_states.iter().enumerate() {
            if i > 0 {
                write!(writer, " \\/ ")?;
            }
            write!(writer, "currentState = {}", state)?;
        }
        writeln!(writer, " )")?;
        writeln!(writer, "THEOREM Spec => Liveness")?;
        writeln!(writer)?;
    }
    
    // Generate safety property: no invalid states
    writeln!(writer, "\\* Safety: always in a valid state")?;
    writeln!(writer, "Safety == [](currentState \\in States)")?;
    writeln!(writer, "THEOREM Spec => Safety")?;
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_machine::{StateMachineBuilder, Transition};
    use std::io::Cursor;

    #[test]
    fn test_generate_simple_tla() {
        let sm = StateMachineBuilder::new("TestMachine".to_string())
            .add_region("main_region".to_string())
                .add_state("State1".to_string())
                    .initial()
                    .add_transition(Transition::new(
                        "t1".to_string(),
                        "State1".to_string(),
                        "State2".to_string(),
                        "Event1".to_string(),
                    ))
                    .finish_state()
                .add_state("State2".to_string())
                    .final_state()
                    .finish_state()
                .finish_region()
            .build();

        let mut output = Cursor::new(Vec::new());
        generate_fsm(&mut output, &sm).unwrap();
        
        let result = String::from_utf8(output.into_inner()).unwrap();
        assert!(result.contains("MODULE TestMachine"));
        assert!(result.contains("State1"));
        assert!(result.contains("State2"));
        assert!(result.contains("Event1"));
        assert!(result.contains("Init =="));
        assert!(result.contains("Next =="));
    }
}