use std::io::Write;
use std::path::Path;
use crate::state_machine::StateMachine;
use crate::Result;
use super::runner::VerificationTool;

/// Configuration for a specific verification tool
#[derive(Debug, Clone)]
pub struct ToolConfig {
    pub tool: VerificationTool,
    pub parameters: std::collections::HashMap<String, String>,
    pub timeout: Option<u64>,
    pub memory_limit: Option<String>,
}

impl ToolConfig {
    pub fn new(tool: VerificationTool) -> Self {
        Self {
            tool,
            parameters: std::collections::HashMap::new(),
            timeout: None,
            memory_limit: None,
        }
    }

    /// Set a parameter for this tool
    pub fn set_parameter(&mut self, key: String, value: String) {
        self.parameters.insert(key, value);
    }

    /// Get optimal configuration based on state machine complexity
    pub fn optimal_for_state_machine(tool: VerificationTool, state_machine: &StateMachine) -> Self {
        let mut config = Self::new(tool.clone());
        
        let state_count = state_machine.states(false).len();
        let transition_count = state_machine.transitions().len();
        let _depth = state_machine.depth();
        
        match tool {
            VerificationTool::Spin => {
                // SPIN configuration based on model size
                if state_count > 50 || transition_count > 100 {
                    config.set_parameter("search".to_string(), "breadth".to_string());
                    config.set_parameter("max_depth".to_string(), "10000".to_string());
                    config.memory_limit = Some("2GB".to_string());
                    config.timeout = Some(600); // 10 minutes
                } else {
                    config.set_parameter("search".to_string(), "depth".to_string());
                    config.set_parameter("max_depth".to_string(), "1000".to_string());
                    config.timeout = Some(300); // 5 minutes
                }
            }
            VerificationTool::TlaPlus => {
                // TLA+ configuration
                config.set_parameter("workers".to_string(), "auto".to_string());
                if state_count > 20 {
                    config.set_parameter("depth".to_string(), "100".to_string());
                    config.timeout = Some(900); // 15 minutes
                } else {
                    config.set_parameter("depth".to_string(), "1000".to_string());
                    config.timeout = Some(300);
                }
            }
            VerificationTool::NuSMV => {
                // NuSMV configuration
                if state_count > 30 {
                    config.set_parameter("dynamic_reorder".to_string(), "true".to_string());
                    config.set_parameter("cone_of_influence".to_string(), "true".to_string());
                    config.timeout = Some(600);
                } else {
                    config.timeout = Some(300);
                }
            }
            VerificationTool::Alloy => {
                // Alloy scope configuration
                let scope = std::cmp::max(state_count + 2, 8);
                config.set_parameter("scope".to_string(), scope.to_string());
                config.timeout = Some(300);
            }
        }
        
        config
    }
}

/// Generate tool-specific configuration files
pub fn generate_tool_config<W: Write>(
    writer: &mut W,
    tool: &VerificationTool,
    config: &ToolConfig,
    state_machine: &StateMachine,
) -> Result<()> {
    match tool {
        VerificationTool::Spin => generate_spin_config(writer, config, state_machine),
        VerificationTool::TlaPlus => generate_tla_config(writer, config, state_machine),
        VerificationTool::NuSMV => generate_nusmv_config(writer, config, state_machine),
        VerificationTool::Alloy => generate_alloy_config(writer, config, state_machine),
    }
}

/// Generate SPIN configuration
fn generate_spin_config<W: Write>(
    writer: &mut W,
    config: &ToolConfig,
    _state_machine: &StateMachine,
) -> Result<()> {
    writeln!(writer, "// SPIN Configuration")?;
    writeln!(writer, "// Generated by upml-rs")?;
    writeln!(writer)?;

    // SPIN uses command-line arguments, so we generate a script
    writeln!(writer, "#!/bin/bash")?;
    writeln!(writer, "# SPIN verification script")?;
    writeln!(writer)?;

    write!(writer, "spin -a")?;
    
    if let Some(search) = config.parameters.get("search") {
        if search == "breadth" {
            write!(writer, " -b")?;
        }
    }
    
    if let Some(depth) = config.parameters.get("max_depth") {
        write!(writer, " -m{}", depth)?;
    }
    
    writeln!(writer, " $1")?;
    writeln!(writer, "gcc -o pan pan.c")?;
    
    write!(writer, "./pan")?;
    
    if let Some(depth) = config.parameters.get("max_depth") {
        write!(writer, " -m{}", depth)?;
    }
    
    writeln!(writer)?;

    Ok(())
}

/// Generate TLA+ configuration
fn generate_tla_config<W: Write>(
    writer: &mut W,
    config: &ToolConfig,
    state_machine: &StateMachine,
) -> Result<()> {
    writeln!(writer, "\\* TLA+ Configuration")?;
    writeln!(writer, "\\* Generated by upml-rs")?;
    writeln!(writer)?;

    writeln!(writer, "SPECIFICATION Spec")?;
    writeln!(writer)?;

    // Add invariants based on state machine
    writeln!(writer, "INVARIANT")?;
    writeln!(writer, "  TypeOK")?;
    
    let states = state_machine.states(false);
    if !states.is_empty() {
        writeln!(writer, "  /\\ state \\in {{{}}}", 
                states.iter().map(|s| format!("\"{}\"", s)).collect::<Vec<_>>().join(", "))?;
    }
    
    writeln!(writer)?;

    // Properties
    writeln!(writer, "PROPERTY")?;
    writeln!(writer, "  Termination")?;
    
    let final_states = state_machine.final_states();
    if !final_states.is_empty() {
        writeln!(writer, "  /\\ <>({{{}}}) \\* Eventually reach final state", 
                final_states.iter().map(|s| format!("state = \"{}\"", s)).collect::<Vec<_>>().join(" \\/ "))?;
    }
    
    writeln!(writer)?;

    // Configuration parameters
    if let Some(depth) = config.parameters.get("depth") {
        writeln!(writer, "\\* Depth limit: {}", depth)?;
    }
    
    if let Some(workers) = config.parameters.get("workers") {
        writeln!(writer, "\\* Workers: {}", workers)?;
    }

    Ok(())
}

/// Generate NuSMV configuration
fn generate_nusmv_config<W: Write>(
    writer: &mut W,
    config: &ToolConfig,
    _state_machine: &StateMachine,
) -> Result<()> {
    writeln!(writer, "-- NuSMV Configuration")?;
    writeln!(writer, "-- Generated by upml-rs")?;
    writeln!(writer)?;

    // NuSMV configuration commands
    if config.parameters.get("dynamic_reorder") == Some(&"true".to_string()) {
        writeln!(writer, "set dynamic_reorder")?;
    }
    
    if config.parameters.get("cone_of_influence") == Some(&"true".to_string()) {
        writeln!(writer, "set cone_of_influence")?;
    }
    
    writeln!(writer, "go")?;
    writeln!(writer, "check_ctlspec")?;
    writeln!(writer, "quit")?;

    Ok(())
}

/// Generate Alloy configuration
fn generate_alloy_config<W: Write>(
    writer: &mut W,
    config: &ToolConfig,
    state_machine: &StateMachine,
) -> Result<()> {
    writeln!(writer, "// Alloy Configuration")?;
    writeln!(writer, "// Generated by upml-rs")?;
    writeln!(writer)?;

    let scope = config.parameters.get("scope")
        .and_then(|s| s.parse::<usize>().ok())
        .unwrap_or(8);

    let states = state_machine.states(false).len();
    let events = state_machine.events().len();
    let transitions = state_machine.transitions().len();

    writeln!(writer, "// Optimal scope based on model size:")?;
    writeln!(writer, "// States: {}, Events: {}, Transitions: {}", states, events, transitions)?;
    writeln!(writer)?;

    writeln!(writer, "// Run commands with optimal scope")?;
    writeln!(writer, "run WellFormed for {} State, {} Event, {} Transition", 
             std::cmp::max(states + 2, scope),
             std::cmp::max(events + 2, scope / 2),
             std::cmp::max(transitions + 5, scope * 2))?;
    
    writeln!(writer, "run {{ WellFormed and Deterministic }} for {} State, {} Event, {} Transition", 
             std::cmp::max(states + 2, scope),
             std::cmp::max(events + 2, scope / 2),
             std::cmp::max(transitions + 5, scope * 2))?;

    Ok(())
}

/// Generate configuration file for a tool
pub fn generate_config_file(
    tool: &VerificationTool,
    config: &ToolConfig,
    state_machine: &StateMachine,
    output_path: &Path,
) -> Result<()> {
    let mut file = std::fs::File::create(output_path)?;
    generate_tool_config(&mut file, tool, config, state_machine)?;
    
    // Make script executable for SPIN
    if tool == &VerificationTool::Spin {
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = file.metadata()?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(output_path, perms)?;
        }
    }
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_machine::StateMachine;

    #[test]
    fn test_tool_config_creation() {
        let config = ToolConfig::new(VerificationTool::Spin);
        assert_eq!(config.tool, VerificationTool::Spin);
        assert!(config.parameters.is_empty());
        assert_eq!(config.timeout, None);
    }

    #[test]
    fn test_optimal_config_generation() {
        let state_machine = StateMachine::new("test".to_string());
        let config = ToolConfig::optimal_for_state_machine(VerificationTool::Spin, &state_machine);
        
        assert_eq!(config.tool, VerificationTool::Spin);
        assert!(config.timeout.is_some());
    }

    #[test]
    fn test_config_generation() {
        let state_machine = StateMachine::new("test".to_string());
        let config = ToolConfig::optimal_for_state_machine(VerificationTool::TlaPlus, &state_machine);
        
        let mut output = Vec::new();
        generate_tool_config(&mut output, &VerificationTool::TlaPlus, &config, &state_machine).unwrap();
        
        let result = String::from_utf8(output).unwrap();
        assert!(result.contains("SPECIFICATION"));
        assert!(result.contains("INVARIANT"));
    }
}